version: '3.8'

services:
  mediabase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mediabase
    ports:
      - "8095:8095" # HTTP Server
      - "8096:8096" # gRPC Server

volumes:
  minio_data:
    driver: local
